version: '3.8'

services:
  # Django server
  django:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - limesurvey

  # Limesurvey server TODO: REMOVE ADMIN PASSWORD!!
  limesurvey:
    # image: docker.io/martialblog/limesurvey:latest
    build:
      context: lime-apache/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=${SQL_PORT}
      - DB_HOST=${SQL_HOST}
      - DB_PASSWORD=${SQL_PASSWORD}
      - DB_NAME=${SQL_DATABASE}
      - DB_USERNAME=${SQL_USER}
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=example
      - ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL=foobar.com
    volumes:
      - limesurvey:/var/www/html/upload/surveys
    expose:
      - 8080:8080
    depends_on:
      - db

  # Postgre shared database
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    expose:
      - 5432:5432

  # Caddy server for reverse proxy
  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - db
      - django
      - limesurvey

volumes:
  limesurvey:
  postgres_data:
  static_volume:
  caddy_data:
    external: true
  caddy_config:
