# Generated by Django 4.1.4 on 2023-01-12 13:45

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ldapgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapgroup',
            name='gid',
            field=ldapdb.models.fields.CharField(db_column='entryUUID', max_length=50, unique=True),
        ),
    ]
