# Generated by Django 4.1.4 on 2023-01-12 21:46

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ldapgroup_gid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapUser',
            fields=[
                ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sn', ldapdb.models.fields.CharField(db_column='sn', max_length=200, unique=True)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True, serialize=False)),
                ('uid', ldapdb.models.fields.CharField(db_column='uid', max_length=200, unique=True)),
                ('email', ldapdb.models.fields.CharField(db_column='mail', max_length=200, unique=True)),
                ('first_name', ldapdb.models.fields.CharField(db_column='displayName', max_length=200, null=True)),
                ('last_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200, null=True)),
                ('password', ldapdb.models.fields.CharField(db_column='userPassword', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ldapgroup',
            name='gid',
        ),
    ]
