# Generated by Django 4.1.4 on 2023-01-12 22:15

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ldapuser_remove_ldapgroup_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuser',
            name='uidNumber',
            field=ldapdb.models.fields.IntegerField(blank=True, db_column='uidNumber', default=0, unique=True),
        ),
    ]
