# Generated by Django 4.1.4 on 2023-01-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ldapuser_uidnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapuser',
            name='uidNumber',
        ),
    ]
