# Generated by Django 4.1.4 on 2023-01-13 07:18

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ldapuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='password',
            field=ldapdb.models.fields.CharField(db_column='userPassword', max_length=128),
        ),
    ]
